service: flask-api

provider:
  name: aws
  runtime: python3.8
  # stage: dev
  # region: 'ap-southeast-1'

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment: # Function level environment variables
      DB_URL: '111'
      DB_USERNAME: '222'
      DB_PASSWORD: '333'
      DB_NAME: '444'

custom:
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - env/**
    - __pycache__/**